[package]
name = "scheme-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = "0.3"
inventory = "0.3"
nom = "7"
rug = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
unicode_categories = "0.1"
